//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{

    public partial class TBUsuarios
    {
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contrasenha { get; set; }
    }
}
