//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVE_Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVE_Clientes()
        {
            this.TVET_Citas = new HashSet<TVET_Citas>();
            this.TVET_Mascotas = new HashSet<TVET_Mascotas>();
        }
    
        public int TN_IdCliente { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_Ap1 { get; set; }
        public string TC_Ap2 { get; set; }
        public string TC_NumTelefono { get; set; }
        public string TC_CorreoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVET_Citas> TVET_Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVET_Mascotas> TVET_Mascotas { get; set; }
    }
}
