//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVET_Mascotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVET_Mascotas()
        {
            this.TVET_Citas = new HashSet<TVET_Citas>();
        }
    
        public int TN_IdMascota { get; set; }
        public string TC_NombreMascota { get; set; }
        public Nullable<int> TN_IdCliente { get; set; }
    
        public virtual TVE_Clientes TVE_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVET_Citas> TVET_Citas { get; set; }
        public virtual TVET_DetalleMascota TVET_DetalleMascota { get; set; }
    }
}
