//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVET_Diagnostico
    {
        public int TN_IdDiagnostico { get; set; }
        public Nullable<int> TN_IdCita { get; set; }
        public string TC_DscDiagnostico { get; set; }
    
        public virtual TVET_Citas TVET_Citas { get; set; }
    }
}
