//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVET_DetalleMascota
    {
        public int TN_IdMascota { get; set; }
        public string TC_Raza { get; set; }
        public decimal TN_Peso { get; set; }
        public string TC_Color { get; set; }
    
        public virtual TVET_Mascotas TVET_Mascotas { get; set; }
    }
}
