//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVET_Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVET_Citas()
        {
            this.TVET_Diagnostico = new HashSet<TVET_Diagnostico>();
        }
    
        public int TN_IdCita { get; set; }
        public Nullable<int> TN_IdCliente { get; set; }
        public Nullable<int> TN_IdMascota { get; set; }
        public System.DateTime TF_FecCita { get; set; }
    
        public virtual TVE_Clientes TVE_Clientes { get; set; }
        public virtual TVET_Mascotas TVET_Mascotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVET_Diagnostico> TVET_Diagnostico { get; set; }
    }
}
