//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.srvLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvLogin.IsrvLogin")]
    public interface IsrvLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvLogin/DoWork", ReplyAction="http://tempuri.org/IsrvLogin/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvLogin/DoWork", ReplyAction="http://tempuri.org/IsrvLogin/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvLogin/iniciarSesion", ReplyAction="http://tempuri.org/IsrvLogin/iniciarSesionResponse")]
        bool iniciarSesion(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvLogin/iniciarSesion", ReplyAction="http://tempuri.org/IsrvLogin/iniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> iniciarSesionAsync(string usuario, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvLoginChannel : UI.srvLogin.IsrvLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvLoginClient : System.ServiceModel.ClientBase<UI.srvLogin.IsrvLogin>, UI.srvLogin.IsrvLogin {
        
        public IsrvLoginClient() {
        }
        
        public IsrvLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool iniciarSesion(string usuario, string password) {
            return base.Channel.iniciarSesion(usuario, password);
        }
        
        public System.Threading.Tasks.Task<bool> iniciarSesionAsync(string usuario, string password) {
            return base.Channel.iniciarSesionAsync(usuario, password);
        }
    }
}
