//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;

    public partial class VeterinariaDBEntities : DbContext
    {
        public VeterinariaDBEntities()
            : base("name=VeterinariaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TVE_Clientes> TVE_Clientes { get; set; }
        public virtual DbSet<TVET_Citas> TVET_Citas { get; set; }
        public virtual DbSet<TVET_DetalleMascota> TVET_DetalleMascota { get; set; }
        public virtual DbSet<TVET_Diagnostico> TVET_Diagnostico { get; set; }
        public virtual DbSet<TVET_Mascotas> TVET_Mascotas { get; set; }
    
        public virtual int spEliminarCitaYDiagnostico(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("IdCita", idCita) :
                new ObjectParameter("IdCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarCitaYDiagnostico", idCitaParameter);
        }
    
        public virtual int spEliminarClienteYRelacionados(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarClienteYRelacionados", idClienteParameter);
        }
    
        public virtual int spEliminarMascotaYDetalles(Nullable<int> idMascota)
        {
            var idMascotaParameter = idMascota.HasValue ?
                new ObjectParameter("IdMascota", idMascota) :
                new ObjectParameter("IdMascota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarMascotaYDetalles", idMascotaParameter);
        }
    }
}
