//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class VPEntidades : DbContext
    {
        public VPEntidades()
            : base("name=VPEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TVE_Clientes> TVE_Clientes { get; set; }
        public virtual DbSet<TVET_Citas> TVET_Citas { get; set; }
        public virtual DbSet<TVET_DetalleMascota> TVET_DetalleMascota { get; set; }
        public virtual DbSet<TVET_Diagnostico> TVET_Diagnostico { get; set; }
        public virtual DbSet<TVET_Mascotas> TVET_Mascotas { get; set; }
    }
}
